# Generated by Django 3.2.3 on 2022-01-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220111_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipefavorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favorite', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
