# Generated by Django 3.2.3 on 2021-12-27 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
    ]
