# Generated by Django 3.2.3 on 2021-12-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_shoppinglist_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipefavorite',
            constraint=models.UniqueConstraint(fields=('author', 'user', 'recipe'), name='favorite_uniq'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='shop_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='subscribe_uniq'),
        ),
        migrations.AlterModelTable(
            name='shoppinglist',
            table='shopping_list',
        ),
        migrations.AlterModelTable(
            name='subscribe',
            table='subscribe',
        ),
    ]
